# Generated by Django 2.2 on 2019-04-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_name', models.CharField(blank=True, max_length=20, null=True)),
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
