# Generated by Django 2.2 on 2019-04-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20190419_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesEnrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('course_name', models.CharField(blank=True, max_length=30, null=True)),
                ('course_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'courses_enrolled',
                'managed': False,
            },
        ),
    ]
