# Generated by Django 2.2 on 2019-04-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_coursesenrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentEnrolled',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sid', models.IntegerField()),
            ],
            options={
                'db_table': 'student_enrolled',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CoursesEnrolled',
        ),
    ]
