# Generated by Django 2.2 on 2019-05-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20190425_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrolled',
            options={},
        ),
    ]
