# Generated by Django 2.2 on 2019-05-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_auto_20190506_1747'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentenrolled',
            unique_together={('course_id', 'sid')},
        ),
        migrations.AlterModelTable(
            name='studentenrolled',
            table='student_enrolled',
        ),
    ]
