# Generated by Django 2.2 on 2019-05-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_auto_20190506_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrolled',
            options={'managed': False},
        ),
    ]
