# Generated by Django 2.2 on 2019-05-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_auto_20190506_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrolled',
            options={'managed': True},
        ),
    ]
