# Generated by Django 2.2 on 2019-05-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_auto_20190506_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTeaches',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'teacher_teaches',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='studentenrolled',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentenrolled',
            name='course_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
