# Generated by Django 2.2 on 2019-05-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_auto_20190506_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrolled',
            options={'managed': False},
        ),
    ]
