# Generated by Django 2.2 on 2019-05-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_feedbackcsn209'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCsn211',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('q1', models.IntegerField(blank=True, null=True)),
                ('q2', models.IntegerField(blank=True, null=True)),
                ('q3', models.IntegerField(blank=True, null=True)),
                ('q4', models.IntegerField(blank=True, null=True)),
                ('q5', models.IntegerField(blank=True, null=True)),
                ('q6', models.IntegerField(blank=True, null=True)),
                ('q7', models.IntegerField(blank=True, null=True)),
                ('q8', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback_csn209',
                'managed': False,
            },
        ),
    ]
