# Generated by Django 2.2 on 2019-05-07 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_feedbackcsn211'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedbackcsn211',
            table='feedback_csn211',
        ),
    ]
